import { Project } from "@/types";

// Static data from AI Agents Portfolio CSV — update when sheet changes
export const STATIC_PROJECTS: Project[] = [
  {
    name: "LLM SEO AI Blogs",
    description: "Produces 25+ AI-optimized articles weekly on Fello and real estate for maximum LLM citations",
    timeline: null,
    llms: [],
    services: [],
    status: "deprecated",
    totalSpend: null,
    openrouter_api_key: null,
  },
  {
    name: "Octo",
    description: "Original Octo — application connector for internal tools",
    timeline: null,
    llms: [{ provider: "Anthropic", model: "Sonnet 4.6", owner: "" }],
    services: [],
    status: "production",
    totalSpend: null,
    openrouter_api_key: "octo",
  },
  {
    name: "Scrapey",
    description: "Auto-enriches Real Estate professional details from Zillow",
    timeline: null,
    llms: [
      { provider: "Perplexity", model: "", owner: "" },
      { provider: "Anthropic", model: "Sonnet 4", owner: "" },
    ],
    services: [],
    status: "deprecated",
    totalSpend: null,
    openrouter_api_key: null,
  },
  {
    name: "30DC God Mode",
    description: "Admin dashboard for the 30-Day Challenge portal",
    timeline: null,
    llms: [{ provider: "OpenAI", model: "GPT-4o-mini", owner: "" }],
    services: [],
    status: "deprecated",
    totalSpend: null,
    openrouter_api_key: null,
  },
  {
    name: "30DC App",
    description: "Real estate team challenge portal with AI chat",
    timeline: null,
    llms: [{ provider: "OpenAI", model: "GPT-4o-mini", owner: "" }],
    services: [],
    status: "deprecated",
    totalSpend: null,
    openrouter_api_key: null,
  },
  {
    name: "BillFlow",
    description: "Spend tracking and sync tool for internal operations",
    timeline: null,
    llms: [{ provider: "OpenAI", model: "GPT-4o-mini", owner: "" }],
    services: [],
    status: "production",
    totalSpend: null,
    openrouter_api_key: "billflow",
  },
  {
    name: "Fia",
    description: "Complete AI Chatbot with Fello.ai product knowledge expertise",
    timeline: null,
    llms: [{ provider: "Google", model: "Gemini Flash", owner: "" }],
    services: [],
    status: "production",
    totalSpend: null,
    openrouter_api_key: "coworking",
  },
  {
    name: "Zillow Scraper",
    description: "Zillow agents and listings scraper for enrichment pipeline",
    timeline: null,
    llms: [],
    services: [],
    status: "deprecated",
    totalSpend: null,
    openrouter_api_key: null,
  },
  {
    name: "30DC Roleplay",
    description: "AI roleplay training for real estate agents with phone simulation",
    timeline: null,
    llms: [],
    services: [],
    status: "production",
    totalSpend: null,
    openrouter_api_key: null,
  },
  {
    name: "MAD (v2)",
    description: "Analytics dashboard for Mega Agent Directory",
    timeline: null,
    llms: [],
    services: [],
    status: "production",
    totalSpend: null,
    openrouter_api_key: "mad (adarsh)",
  },
  {
    name: "Team Size Webhook",
    description: "Webhook service for team size enrichment pipeline",
    timeline: null,
    llms: [
      { provider: "xAI", model: "Grok", owner: "" },
      { provider: "OpenAI", model: "GPT-4o-mini", owner: "" },
    ],
    services: [],
    status: "production",
    totalSpend: null,
    openrouter_api_key: null,
  },
  {
    name: "YoungTeam Octo",
    description: "Young Team variant of Octo connector",
    timeline: null,
    llms: [],
    services: [],
    status: "production",
    totalSpend: null,
    openrouter_api_key: "octo",
  },
  {
    name: "CRM Agent",
    description: "Enriching CRM data for MAD using web scraping",
    timeline: null,
    llms: [{ provider: "xAI", model: "Grok", owner: "" }],
    services: [],
    status: "production",
    totalSpend: null,
    openrouter_api_key: null,
  },
  {
    name: "Social Media Agent",
    description: "Enriching social media presence data for MAD",
    timeline: null,
    llms: [{ provider: "Google", model: "Gemini", owner: "" }],
    services: [],
    status: "production",
    totalSpend: null,
    openrouter_api_key: null,
  },
  {
    name: "Real Estate Team Analyser",
    description: "Multi-agent system gathering team transactions",
    timeline: null,
    llms: [],
    services: [],
    status: "production",
    totalSpend: null,
    openrouter_api_key: null,
  },
  {
    name: "GTM Digital Office",
    description: "AI Chief of Staff — Orin bot across Google Chat & Slack",
    timeline: null,
    llms: [{ provider: "xAI", model: "Grok-4", owner: "" }],
    services: [],
    status: "prototype",
    totalSpend: null,
    openrouter_api_key: "GTM-Digital-Office",
  },
  {
    name: "Fello Designer Portal",
    description: "Internal design portal for the Fello team",
    timeline: null,
    llms: [],
    services: [],
    status: "prototype",
    totalSpend: null,
    openrouter_api_key: "fello-designer-portal",
  },
  {
    name: "AI Resume Analyser",
    description: "Ranks top candidates from application pools based on requirements",
    timeline: null,
    llms: [{ provider: "Alibaba", model: "Qwen 3.5", owner: "" }],
    services: [],
    status: "production",
    totalSpend: null,
    openrouter_api_key: null,
  },
  {
    name: "Pipeline Monitor",
    description: "Mega Agent Dashboard — enriching US Real Estate professionals and teams",
    timeline: null,
    llms: [],
    services: [],
    status: "production",
    totalSpend: null,
    openrouter_api_key: "mad (adarsh)",
  },
  {
    name: "SignalCards",
    description: "",
    timeline: null,
    llms: [{ provider: "OpenRouter", model: "", owner: "" }],
    services: [],
    status: "r&d",
    totalSpend: null,
    openrouter_api_key: "signalcards(boduu)",
  },
  {
    name: "Data Pilot",
    description: "Comprehensive data operations supporting Sales Marketing and RevOps",
    timeline: null,
    llms: [],
    services: [],
    status: "production",
    totalSpend: null,
    openrouter_api_key: "mad (adarsh)",
  },
  {
    name: "Felix Job Application",
    description: "",
    timeline: null,
    llms: [],
    services: [],
    status: "prototype",
    totalSpend: null,
    openrouter_api_key: null,
  },
  {
    name: "Customer Support 30DC",
    description: "Customer support agent for 30-Day Challenge platform",
    timeline: null,
    llms: [],
    services: [],
    status: "deprecated",
    totalSpend: null,
    openrouter_api_key: null,
  },
  {
    name: "Miro Fish",
    description: "Experimental Miro integration tool",
    timeline: null,
    llms: [],
    services: [],
    status: "deprecated",
    totalSpend: null,
    openrouter_api_key: "mirofish",
  },
  {
    name: "DB Health Report Quiz",
    description: "Comprehensive agent database diagnostics through intelligent questioning",
    timeline: null,
    llms: [{ provider: "OpenAI", model: "GPT-4", owner: "" }],
    services: [],
    status: "testing",
    totalSpend: null,
    openrouter_api_key: null,
  },
  {
    name: "HubSpot LLM Wiki",
    description: "LLM-powered wiki for HubSpot knowledge base",
    timeline: null,
    llms: [],
    services: [],
    status: "r&d",
    totalSpend: null,
    openrouter_api_key: null,
  },
  {
    name: "LibreChat",
    description: "Self-hosted LibreChat instance for internal AI experimentation",
    timeline: null,
    llms: [],
    services: [],
    status: "r&d",
    totalSpend: null,
    openrouter_api_key: null,
  },
  {
    name: "Churn Call Analysis",
    description: "Comprehensive chronological report on churned client calls",
    timeline: null,
    llms: [],
    services: [],
    status: "deprecated",
    totalSpend: null,
    openrouter_api_key: null,
  },
  {
    name: "AI SDR",
    description: "Identified website visitors and sent personalized outreach",
    timeline: null,
    llms: [],
    services: [],
    status: "deprecated",
    totalSpend: null,
    openrouter_api_key: null,
  },
  {
    name: "Reddit Mentions",
    description: "Real-time monitoring of brand mentions and discussions on Reddit",
    timeline: null,
    llms: [],
    services: [],
    status: "deprecated",
    totalSpend: null,
    openrouter_api_key: null,
  },
  {
    name: "Product Marketing AI",
    description: "Real-time competitive gap analysis identifying opportunities against competitors",
    timeline: null,
    llms: [],
    services: [],
    status: "deprecated",
    totalSpend: null,
    openrouter_api_key: null,
  },
  {
    name: "Testimonial Agent",
    description: "Converts customer call recordings into testimonial blogs",
    timeline: null,
    llms: [{ provider: "OpenAI", model: "GPT-4o-mini", owner: "" }],
    services: [],
    status: "deprecated",
    totalSpend: null,
    openrouter_api_key: null,
  },
  {
    name: "Felix Sells",
    description: "",
    timeline: null,
    llms: [],
    services: [],
    status: "prototype",
    totalSpend: null,
    openrouter_api_key: "Felix Sells",
  },
  {
    name: "Felix Wins",
    description: "",
    timeline: null,
    llms: [],
    services: [],
    status: "production",
    totalSpend: null,
    openrouter_api_key: null,
  },
  {
    name: "Felix Command Center",
    description: "",
    timeline: null,
    llms: [],
    services: [],
    status: "production",
    totalSpend: null,
    openrouter_api_key: "felix-launch-command-center",
  },
  {
    name: "Atrium",
    description: "",
    timeline: null,
    llms: [],
    services: [],
    status: "prototype",
    totalSpend: null,
    openrouter_api_key: "ATRIUM - Agnetic real estate - Hemanth",
  },
  {
    name: "Arthur for Fello",
    description: "",
    timeline: null,
    llms: [],
    services: [],
    status: "production",
    totalSpend: null,
    openrouter_api_key: "blog-writter-code",
  },
  {
    name: "Arthur for Young Team",
    description: "",
    timeline: null,
    llms: [],
    services: [],
    status: "production",
    totalSpend: null,
    openrouter_api_key: "blog-writter-code",
  },
  {
    name: "Arthur Audit",
    description: "",
    timeline: null,
    llms: [],
    services: [],
    status: "production",
    totalSpend: null,
    openrouter_api_key: "aurthur_audit",
  },
  {
    name: "Scrapey 2 (code)",
    description: "",
    timeline: null,
    llms: [],
    services: [],
    status: "production",
    totalSpend: null,
    openrouter_api_key: "scrrpy(code version)",
  },
  {
    name: "Meta Ads",
    description: "",
    timeline: null,
    llms: [],
    services: [],
    status: "prototype",
    totalSpend: null,
    openrouter_api_key: null,
  },
  {
    name: "Webinar Enrichment",
    description: "",
    timeline: null,
    llms: [],
    services: [],
    status: "production",
    totalSpend: null,
    openrouter_api_key: null,
  },
  {
    name: "Felix Actor",
    description: "",
    timeline: null,
    llms: [],
    services: [],
    status: "deprecated",
    totalSpend: null,
    openrouter_api_key: null,
  },
  {
    name: "Arthur Crawler (brain)",
    description: "",
    timeline: null,
    llms: [],
    services: [],
    status: "production",
    totalSpend: null,
    openrouter_api_key: "aurthur_audit",
  },
  {
    name: "Fello Academy",
    description: "AI-powered learning platform for Fello team",
    timeline: null,
    llms: [],
    services: [],
    status: "production",
    totalSpend: null,
    openrouter_api_key: "Fello_Academy_Main, Fello_Academy_Backup",
  },
  {
    name: "Fello Competitor Analysis",
    description: "Competitive intelligence and market analysis tool",
    timeline: null,
    llms: [],
    services: [],
    status: "production",
    totalSpend: null,
    openrouter_api_key: null,
  },
  {
    name: "Marketing Labs",
    description: "Marketing experimentation and automation platform",
    timeline: null,
    llms: [],
    services: [],
    status: "production",
    totalSpend: null,
    openrouter_api_key: "Marketing Labs - Hemanth",
  },
  {
    name: "OpenClaw - Nikhil",
    description: "",
    timeline: null,
    llms: [],
    services: [],
    status: "r&d",
    totalSpend: null,
    openrouter_api_key: "openclaw (nikhil)",
  },
  {
    name: "OpenClaw - Riyon",
    description: "",
    timeline: null,
    llms: [],
    services: [],
    status: "r&d",
    totalSpend: null,
    openrouter_api_key: "openclaw(riyon)",
  },
  {
    name: "OpenClaw - Aryan",
    description: "",
    timeline: null,
    llms: [],
    services: [],
    status: "r&d",
    totalSpend: null,
    openrouter_api_key: "spiderclaw",
  },
];

export async function getProjects(): Promise<Project[]> {
  return STATIC_PROJECTS;
}
